<?php

$this->title = "#{$this->channel->name}";
$this->messages = Message::search(array('channel_id' => $this->channel->id));

$timezoom_offset = date('Z');
$sql = "SELECT FLOOR((ts + {$timezoom_offset}) / 86400), COUNT(*) FROM message WHERE channel_id = '{$this->channel->id}' GROUP BY FLOOR((ts + {$timezoom_offset}) / 86400)";
$res = Message::getDb()->query($sql);
$month_count = array();
while ($row = $res->fetch_array()) {
    list($t, $count) = $row;
    $t = $t * 86400 + $timezoom_offset;
    $month = date('Y-m', $t);
    if (!array_key_exists($month, $month_count)) {
        $month_count[$month] = 0;
    }
    $month_count[$month] += $count;
}
ksort($month_count);

if ($this->next_date) {
    $range_term = "ts >= {$this->current_date} AND ts < {$this->next_date}";
} else {
    $range_term = "ts >= {$this->current_date}";
}
$thread_tss = $this->messages->search($range_term)->toArray('ts');
if ($thread_tss) {
    $reply_threads = Message::search(array('channel_id' => $this->channel->id))->search("(data->>'thread_ts')::NUMERIC IN (" . implode(',', $thread_tss) . ")");
    $reply_messages = array();
    foreach ($reply_threads as $reply) {
        $data = json_decode($reply->data);
        if ($data->thread_ts == $reply->ts) {
            continue;
        }
        if (!array_key_exists($data->thread_ts, $reply_messages)) {
            $reply_messages[$data->thread_ts] = array();
        }
        $reply_messages[floatval($data->thread_ts)][$reply->ts] = $reply;
    }
}
?>
<?= $this->partial('common/header.phtml', $this) ?>

<style>
.emoji {
    font-size: 16px;
    vertical-align: middle;
}

.attachment-image {
    aspect-ratio: auto;
}

@media screen and (min-width: 48rem) {
    .attachment-image {
        max-width: 24rem;
        max-height: 24rem;
    }
}
</style>

<div class="container my-4">

<h2><?php if ($this->channel->is_channel) { ?>#<?php } elseif ($this->channel->is_group) { ?><i class="bi bi-lock-fill me-1" aria-hidden="true"></i><?php } ?><?= $this->escape($this->channel->name) ?></h2>

<nav>
    <ul class="pagination">
    <?php foreach ($month_count as $month => $count) { ?>
    <li <?= (date('Y-m', $this->current_date) == $month) ? ' class="active"': ''?>>
    <a href="/index/channel/<?= $this->channel->id ?>/<?= $month ?>"><?= $month ?>
        (<?= $count ?>)
    </a>
    </li>
    <?php } ?>
    </ul>
</nav>

<section role="feed">
    <?php $current_date = null; ?>
    <?php foreach ($this->messages->search($range_term)->order('ts ASC') as $message) { ?>
    <?php if (is_null($current_date) or date('Y-m-d', $message->ts) != $current_date) { ?>
        <?php $current_date = date('Y-m-d', $message->ts) ?>
        <h5 class="my-3"><?= $current_date ?></h5>
    <?php } ?>
    <?= $this->partial('/index/message.phtml', array('message' => $message, 'replies' => $reply_messages[floatval($message->ts)])) ?>
    <?php } ?>
</section>

<?= $this->partial('common/footer.phtml', $this) ?>
