<?php

$this->title = "#{$this->channel->name}";
$this->messages = Message::search(array('channel_id' => $this->channel->id));

$timezoom_offset = date('Z');
$sql = "SELECT FLOOR((ts + {$timezoom_offset}) / 86400), COUNT(*) FROM message WHERE channel_id = '{$this->channel->id}' GROUP BY FLOOR((ts + {$timezoom_offset}) / 86400)";
$res = Message::getDb()->query($sql);

$year_month_count = array();
while ($row = $res->fetch_array()) {
    list($t, $count) = $row;
    $t = $t * 86400 + $timezoom_offset;

    $year = date('Y', $t);
    $month = date('Y-m', $t);

    if (!array_key_exists($year, $year_month_count)) {
        $year_month_count[$year] = array();
    }

    if (!array_key_exists($month, $year_month_count[$year])) {
        $year_month_count[$year][$month] = 0;
    }

    $year_month_count[$year][$month] += $count;
}

ksort($year_month_count);
foreach ($year_month_count as $year => &$month_count) {
    ksort($month_count);
}

if ($this->next_date) {
    $range_term = "ts >= {$this->current_date} AND ts < {$this->next_date}";
} else {
    $range_term = "ts >= {$this->current_date}";
}
$thread_tss = $this->messages->search($range_term)->toArray('ts');
if ($thread_tss) {
    $reply_threads = Message::search(array('channel_id' => $this->channel->id))->search("(data->>'thread_ts')::NUMERIC IN (" . implode(',', $thread_tss) . ")");
    $reply_messages = array();
    foreach ($reply_threads as $reply) {
        $data = json_decode($reply->data);
        if ($data->thread_ts == $reply->ts) {
            continue;
        }
        if (!array_key_exists($data->thread_ts, $reply_messages)) {
            $reply_messages[$data->thread_ts] = array();
        }
        $reply_messages[floatval($data->thread_ts)][$reply->ts] = $reply;
    }
}
?>
<?= $this->partial('common/header.phtml', $this) ?>

<style>
.badge .emoji {
    font-size: 16px;
}

.badge .emoji > img {
    aspect-ratio: auto;
    max-width: 16px;
    max-height: 16px;
}

.attachment-image {
    aspect-ratio: auto;
}

@media screen and (min-width: 48rem) {
    .attachment-image {
        max-width: 24rem;
        max-height: 24rem;
    }
}

.message.thread-message {
    display: none;
}
</style>

<div class="container my-4">

<h2><?php if ($this->channel->is_channel) { ?>#<?php } elseif ($this->channel->is_group) { ?><i class="bi bi-lock-fill me-1" aria-hidden="true"></i><?php } ?><?= $this->escape($this->channel->name) ?></h2>

<nav role="pagination">
    <ul class="nav nav-tabs">
        <?php foreach ($year_month_count as $year => $month_count) { ?>
        <li class="nav-item">
            <?php if (date('Y', $this->current_date) == $year) { ?>
            <?php $this_month = date('Y-m', $this->current_date) ?>
            <a class="nav-link active dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" href="/index/channel/<?= $this->channel->id ?>/<?= $this_month ?>" aria-label="<?= $year ?>"><?= $this_month ?></a>
            <?php } else { ?>
            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false" href="/index/channel/<?= $this->channel->id ?>/<?= array_key_first($month_count) ?>"><?= $year ?></a>
            <?php } ?>
            <ul class="dropdown-menu">
                <?php foreach ($month_count as $month => $count) { ?>
                <li><a class="dropdown-item" href="/index/channel/<?= $this->channel->id ?>/<?= $month ?>"><?= $month ?><span class="badge rounded-pill text-primary bg-primary-subtle ms-1" aria-label="<?= $count ?> messages"><?= $count ?></span></a></li>
                <?php } ?>
            </ul>
        </li>
    </ul>
</nav>

<section role="feed">
    <?php $current_date = null; ?>
    <?php foreach ($this->messages->search($range_term)->order('ts ASC') as $message) { ?>
    <?php if (is_null($current_date) or date('Y-m-d', $message->ts) != $current_date) { ?>
        <?php $current_date = date('Y-m-d', $message->ts) ?>
        <h5 class="my-3"><?= $current_date ?></h5>
    <?php } ?>
    <?= $this->partial('/index/message.phtml', array('message' => $message, 'replies' => $reply_messages[floatval($message->ts)])) ?>
    <?php } ?>
</section>

</div>

<?= $this->partial('common/footer.phtml', $this) ?>
