<?php
$sql = "SELECT channel_id, count(*), max(ts) FROM message GROUP BY channel_id";
$res = Message::getDb()->query($sql);
$channel_count = array();
while ($row = $res->fetch_array()) {
    $channel_count[$row[0]] = array($row[1], $row[2]);
}
?>
<?= $this->partial('common/header.phtml', $this) ?>
<?php if ($this->private_channel) { ?>
<h1>Private Channels</h1>
<table class="table">
    <thead>
        <tr>
            <th>Channel</th>
            <th>Topic</th>
            <th>Created</th>
            <th>Message count</th>
            <th>Latest posted</th>
            <th>Latest synced</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($this->private_channel as $private_channel) { ?>
    <?php if (!$channel = Channel::find($private_channel)) { continue; } ?>
    <?php $data = json_decode($channel->data) ?>
    <tr>
        <td>
            <a href="/index/channel/<?= $channel->id ?>" title="<?= $this->escape(($channel->data)) ?>"><?= $channel->name ?></a>
        </td>
        <td><?= $this->escape($data->topic->value) ?></td>
        <td> <?= date('Y/m/d H:i:s', $data->created) ?> </td>
        <?php $private_config = json_decode($channel->private_config) ?>
        <?php if (property_exists($private_config, 'access_token')) { ?>
        <td><?= $channel_count[$channel->id][0] ?></td>
        <td><?= date('Y/m/d H:i:s', $channel_count[$channel->id][1])?></td>
        <td>
            <?php if ($channel->last_fetched_at) { ?>
            <?= date('Y/m/d H:i:s', $channel->last_fetched_at) ?>
            <?php } else { ?>
            not yet
            <?php } ?>
        </td>
        <?php } else { ?>
        <td colspan="3">
            <form method="post" action="/index/addprivatechannel?channel=<?= urlencode($channel->id) ?>">
               <button type="submit">開始同步</button>
            </form>
        </td>
        <?php } ?>
    </tr>
    <?php } ?>
    </tbody>
</table>
<?php } ?>
<h1>Public Channels</h1>
<table class="table">
    <thead>
        <tr>
            <th>Channel</th>
            <th>Topic</th>
            <th>Created</th>
            <th>Message count</th>
            <th>Latest posted</th>
            <th>Latest synced</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach (Channel::search(1) as $channel) { ?>
    <?php $data = json_decode($channel->data) ?>
    <?php if (property_exists($data, 'is_private') and $data->is_private) { continue; } ?>
    <tr>
        <td>
            <a href="/index/channel/<?= $channel->id ?>" title="<?= $this->escape(($channel->data)) ?>"><?= $channel->name ?></a>
        </td>
        <td><?= $this->escape($data->topic->value) ?></td>
        <td> <?= date('Y/m/d H:i:s', $data->created) ?> </td>
        <td><?= $channel_count[$channel->id][0] ?></td>
        <td><?= date('Y/m/d H:i:s', $channel_count[$channel->id][1])?></td>
        <td>
            <?php if ($channel->last_fetched_at) { ?>
            <?= date('Y/m/d H:i:s', $channel->last_fetched_at) ?>
            <?php } else { ?>
            not yet
            <?php } ?>

        </td>
    <?php } ?>
    </tbody>
</ul>

<?= $this->partial('common/footer.phtml', $this) ?>
