<?php
$sql = "SELECT channel_id, count(*), max(ts) FROM message GROUP BY channel_id";
$res = Message::getDb()->query($sql);
$channel_count = array();
while ($row = $res->fetch_array()) {
    $channel_count[$row[0]] = array($row[1], $row[2]);
}
$channels = array();
foreach (Channel::search(1)  as $channel) {
    $channels[] = $channel;
}
usort($channels, function($a, $b) {
    $dataa = json_decode($a->data);
    $datab = json_decode($b->data);

    return $datab->num_members - $dataa->num_members;

});
?>
<?= $this->partial('common/header.phtml', $this) ?>

<style>
.table thead.position-sticky {
    top: 3.5rem;
}

.table th[scope="row"] {
    max-width: 12em;
}

.message a, .channel {
    word-break: break-word;
    text-wrap: balance;
}
</style>

<?php if ($this->private_channel) { ?>
<section class="table-responsive-lg">
<table class="table table-hover caption-top">
    <caption class="text-body-emphasis">
        <h2 class="h4">Private Channels</h2>
    </caption>
    <thead class="position-sticky">
        <tr>
            <th scope="col">Channel</th>
            <th scope="col">Topic</th>
            <th scope="col">Description</th>
            <th scope="col">Created</th>
            <th scope="col">Messages</th>
            <th scope="col">Members</th>
            <th scope="col">Last Posted</th>
            <th scope="col">Last Synced</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->private_channel as $private_channel) { ?>
        <?php if (!$channel = Channel::find($private_channel)) { continue; } ?>
        <?php $data = json_decode($channel->data) ?>
        <tr>
            <th scope="row">
                <a class="channel" href="/index/channel/<?= $channel->id ?>" title="<?= $this->escape(($channel->data)) ?>"><i class="bi bi-lock-fill me-1" aria-hidden="true"></i><?= $channel->name ?></a>
            </th>
            <td class="message"><?= Message::getHTML($data->topic->value) ?></td>
            <td class="message"><?= Message::getHTML($data->purpose->value) ?></td>
            <td><?= date('Y/m/d H:i:s', $data->created) ?> </td>
        <?php $private_config = json_decode($channel->private_config) ?>
        <?php if (property_exists($private_config, 'access_token')) { ?>
            <td class="text-end"><?= $channel_count[$channel->id][0] ?></td>
            <td class="text-end"><?= $data->num_members ?></td>
            <td><?= date('Y/m/d H:i:s', $channel_count[$channel->id][1])?></td>
            <td>
                <?php if ($channel->last_fetched_at) { ?>
                    <?= date('Y/m/d H:i:s', $channel->last_fetched_at) ?>
                <?php } else { ?>
                    not yet
                <?php } ?>
            </td>
            <td>
                <form method="post" action="/index/addprivatechannel?channel=<?= urlencode($channel->id) ?>">
                    <button class="btn btn-outline-secondary btn-sm" type="submit" title="手動同步"><i class="bi bi-arrow-clockwise" aria-hidden="true"></i></button>
                </form>
            </td>
        <?php } else { ?>
            <td colspan="4"></td>
            <td>
                <form method="post" action="/index/addprivatechannel?channel=<?= urlencode($channel->id) ?>">
                    <button class="btn btn-outline-primary btn-sm" type="submit" title="開始同步"><i class="bi bi-cloud-download" aria-hidden="true"></i></button>
                </form>
            </td>
        <?php } ?>
        </tr>
        <?php } ?>
    </tbody>
</table>
</section>
<?php } ?>

<section class="table-responsive-lg">
<table class="table table-hover caption-top">
    <caption class="text-body-emphasis">
        <h2 class="h4">Public Channels</h2>
    </caption>
    <thead class="position-sticky">
        <tr>
            <th scope="col">Channel</th>
            <th scope="col">Topic</th>
            <th scope="col">Description</th>
            <th scope="col">Created</th>
            <th scope="col">Messages</th>
            <th scope="col">Members</th>
            <th scope="col">Last Posted</th>
            <th scope="col">Last Synced</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($channels as $channel) { ?>
        <?php $data = json_decode($channel->data) ?>
        <?php if (property_exists($data, 'is_private') and $data->is_private) { continue; } ?>
        <tr>
            <th scope="row">
                <a class="channel" href="/index/channel/<?= $channel->id ?>" title="<?= $this->escape(($channel->data)) ?>">#<?= $channel->name ?></a>
            </th>
            <td class="message"><?= Message::getHTML($data->topic->value) ?></td>
            <td class="message"><?= Message::getHTML($data->purpose->value) ?></td>
            <td><?= date('Y/m/d H:i:s', $data->created) ?></td>
            <td class="text-end"><?= $channel_count[$channel->id][0] ?></td>
            <td class="text-end"><?= $data->num_members ?></td>
            <td><?= date('Y/m/d H:i:s', $channel_count[$channel->id][1])?></td>
            <td>
                <?php if ($channel->last_fetched_at) { ?>
                    <?= date('Y/m/d H:i:s', $channel->last_fetched_at) ?>
                <?php } else { ?>
                    not yet
                <?php } ?>
            </td>
        </tr>
        <?php } ?>
    </tbody>
</table>
</section>

<?= $this->partial('common/footer.phtml', $this) ?>
