<?php
$message_data = json_decode($this->message->data);
if ($message_data->user and $user = User::find($message_data->user)) {
    $user_data = json_decode($user->data);
    $avatar = $user_data->profile->image_72;
    if ($user_data->profile->display_name) {
        $user_name = $user_data->profile->display_name;
    } else {
        $user_name = $user_data->name;
    }
} else {
    $avatar = 'https://ca.slack-edge.com/T02G2SXKM-UD94JT3KQ-g8c100274e62-48';
    $user_name = '@' . $message_data->user;
}

$generated_text = '';
$text = $message_data->text;
while (true) {
    if (strpos($text, '<') === false) {
        $text = str_replace('&lt;', '<', $text);
        $text = str_replace('&gt;', '>', $text);
        $generated_text .= nl2br(htmlspecialchars($text));
        break;
    }
    list($plain_text, $other) = explode('<', $text, 2);
    $plain_text = str_replace('&lt;', '<', $plain_text);
    $plain_text = str_replace('&gt;', '>', $plain_text);
    $generated_text .= nl2br(htmlspecialchars($plain_text));

    list($special_text, $text) = explode('>', $other, 2);
    if ($special_text[0] == '@') {
        if (!$user = User::find(ltrim($special_text, '@'))) {
            $name = '@' . $matches[1];
        } else {
            $name = '@' . $user->name;
        }
        $generated_text .= '<b>' . nl2br(htmlspecialchars($name)) . '</b>';
    } elseif (strpos($special_text, 'http') === 0) {
        $generated_text .= sprintf("<a href=\"%s\">%s</a>", htmlspecialchars($special_text), htmlspecialchars($special_text));
    } elseif (preg_match("/^#(.*)\|(.*)$/", $special_text, $matches)) {
        $generated_text .= sprintf("<a href=\"/index/channel/%s\">#%s</a>", htmlspecialchars($matches[1]), htmlspecialchars($matches[2]));
    } else {
        $generated_text .= '&lt;' . $special_text . '&gt;';
    }
}
$style = '';
if ($message_data->thread_ts and !$message_data->is_thread_broadcast) {
    $style = "display:none";
}
?>
<div class="message" style="<?= $style ?>" id="ts-<?= $this->message->ts?>">
    <div class="avatar">
        <img src="<?= $this->escape($avatar) ?>" width="36" height="36">
    </div>
    <div class="content">
        <div>
            <span class="user-name" title="<?= htmlspecialchars(json_encode($user_data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?>"><strong><?= $this->escape($user_name) ?></strong></span>
            <span class="message-time" title="<?= htmlspecialchars(json_encode($message_data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT)) ?>"><a href="#ts-<?= $this->message->ts ?>"><?= date('H:i:s', $this->message->ts) ?></a></span>
        </div>
        <div><?= $generated_text ?></div>
    </div>
</div>
