<?php

$this->title = "# Search [{$this->q}]";
$this->messages = Message::search('data->>\'text\' LIKE ' . Message::getDb()->quoteWithColumn('data', "%{$this->q}%"))->limit(100);

$channel_ids = [];
$messages = [];
foreach ($this->messages as $message) {
    $channel_ids[$message->channel_id] = $message->channel_id;
    $messages[] = $message;
}
usort($messages, fn($a, $b) => ($b->ts - $a->ts));

$channels = [];
if ($channel_ids) {
    foreach (Channel::search(1)->searchIn('id', array_keys($channel_ids)) as $channel) {
        $data = json_decode($channel->data);
        if ($data->is_private) {
            if (!$this->user->id) {
                continue;
            }
            if (!ChannelUser::search(['channel_id' => $channel->id, 'user_id' => $this->user->id])->count()) {
                continue;
            }
        }
        $channels[$channel->id] = $channel;
    }
}

?>
<?= $this->partial('common/header.phtml', $this) ?>
<style>
.badge .emoji {
    font-size: 16px;
}

.badge .emoji > img {
    aspect-ratio: auto;
    max-width: 16px;
    max-height: 16px;
}

.attachment-image {
    aspect-ratio: auto;
}

@media screen and (min-width: 48rem) {
    .attachment-image {
        max-width: 24rem;
        max-height: 24rem;
    }
}
</style>

<section class="container my-4">
    <h2>Search: <q class="text-body-secondary small"><?= $this->escape($this->q) ?></q></h2>
    <ol class="list-group my-4" aria-label="Results">
    <?php foreach ($messages as $message) {
        if (!array_key_exists($message->channel_id, $channels)) { continue; } ?>
        <li class="list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between mb-1">
                <strong>#<?= $this->escape($channels[$message->channel_id]->name) ?></strong>
                <a href="/index/channel/<?= $message->channel_id ?>/<?= date('Y-m', $message->ts) ?>#ts-<?= $message->ts ?>" class="link-secondary small stretched-link"><?= date('Y-m-d H:i:s', $message->ts) ?></a>
            </div>
            <?= $this->partial('/index/message.phtml', ['message' => $message]) ?>
        </li>
    <?php } ?>
    </ol>
</section>

<?= $this->partial('common/footer.phtml', $this) ?>
