<?php

$title_terms = array();
if ($this->title) {
    $title_terms[] = $this->title;
}

if (getenv('WORKSPACE_NAME')) {
    $title_terms[] = getenv('WORKSPACE_NAME');
}

$title_terms[] = 'slack archive';
?>
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title><?= $this->escape(implode(' | ', $title_terms)) ?></title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
<?php if (getenv('GOOGLEANALYTICS_ACCOUNT')) { ?>
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', <?= json_encode(getenv('GOOGLEANALYTICS_ACCOUNT')) ?>]);
_gaq.push(['_trackPageview']);

(function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
})();
</script>
<?php } ?>
</head>
<body class="<?= $this->escape($this->body_class) ?>">
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/">Slack archive</a>
        <ul class="nav">
            <li>
            <a href="/">Channels</a>
            </li>
            <li>
            <a href="https://github.com/ronnywang/g0v-slack-archive">Source Code</a>
            </li>
            <?php if ($this->user) { ?>
            <li class="dropdown">
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">Hi! <?= $this->escape($this->user->name) ?><b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li class="divider"></li>
                <li><a href="/index/logout">登出</a></li>
            </ul>
            </li>
            <?php } else { ?>
            <li>
            <a href="/index/login/">Login with Slack</a>
            </li>
            <?php } ?>
        </ul>
        <div class="nav-collapse collapse">
            <form class="navbar-form pull-right" method="get" action="/index/search">
                <input type="text" name="q" placeholder="search">
            </form>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row-fluid">
